export const FETCH_SERVICES_START = "FETCH_SERVICES_START";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_FAIL = "FETCH_SERVICES_FAIL";

export const SET_REDIRECT_PATH = "SET_REDIRECT_PATH";

export const FETCH_SERVICE_START = "FETCH_SERVICE_START";
export const FETCH_SERVICE_SUCCESS = "FETCH_SERVICE_SUCCESS";
export const FETCH_SERVICE_FAIL = "FETCH_SERVICE_FAIL";

export const FETCH_OPERATIONS_START = "FETCH_OPERATIONS_START";
export const FETCH_OPERATIONS_SUCCESS = "FETCH_OPERATIONS_SUCCESS";
export const FETCH_OPERATIONS_FAIL = "FETCH_OPERATIONS_FAIL";

export const FETCH_SERVICE_LOG_START = "FETCH_SERVICE_LOG_START";
export const FETCH_SERVICE_LOG_SUCCESS = "FETCH_SERVICE_LOG_SUCCESS";
export const FETCH_SERVICE_LOG_FAIL = "FETCH_SERVICE_LOG_FAIL";

export const ADD_OPERATION = "ADD_OPERATION";
export const REMOVE_OPERATION = "REMOVE_OPERATION";
export const CLOSE_OPERATIONS = "CLOSE_OPERATIONS";
